### PR TITLE
Bug fix/203 orange line has no link

### PR DESCRIPTION
**Pull request by anusharanganathan**
I removed the link, but this also meant the underline disappeared (commit bbd450d).

To fix this, I have added an underline tag and modified the relevant scss and css files (commit 9b8c1b8). Underline was deprecated and then re-introduced in html5. I am not sure if this is the best way to have done it. Also this touches upon what @sssoz does. The underline is now applied globally. So I am happy to roll back this commit before it is pushed to dev, if it rather be handled a different way.

### CODE REVIEW

**Comment by sssoz** [comment]
Only links should be underlined; adding an underline that looks like a link is confusing...The underline was removed because the link that was supposed to be there was originally meant to open a modal containing the "Explain this result" content. 

I would not recommend using the `<u>` element in this way as it is meant to semantically identify an annotation.

**Comment by sssoz** [comment]
See https://github.com/antleaf/jct-project/issues/203

**Comment by richard-jones** [comment]
Ok, so I think the right thing to do here is just to remove the `a` tag and leave it at that

**Comment by anusharanganathan** [comment]
I have reverted that commit.

**Pull request merged**
